project:
  type: website
  output-dir: docs

website:
  title: "My Personal Website for STAT 37815"
  navbar:
   left:
    - href: index.qmd
      text: Home
    - about.qmd
   tools:
    - icon: github
      href: https://github.com/buningF/buningF.github.io
format:
  html:
    theme: minty
    mainfont: "'Montserrat', sans-serif"
    # css: my-style.css
    # toc: true
